project:
  type: website
  output-dir: docs 

format:
  html:
    theme: statlab.scss
    css: styles.css
    toc: true


execute: 
  eval: false

website:
  title: "Yale Library StatLab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research-guides.qmd
        text: "Research Guides"
      # Leave room for your future sections:
      # - href: workshops.qmd
      #   text: Workshops
      # - href: resources.qmd  
      #   text: Resources
      # - href: consulting.qmd
      #   text: Consulting




