project:
  type: website


execute: 
  eval: false

website:
  title: "YUL StatLab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research-guides.qmd
        text: "Research Guides"
      # Leave room for your future sections:
      # - href: workshops.qmd
      #   text: Workshops
      # - href: resources.qmd  
      #   text: Resources
      # - href: consulting.qmd
      #   text: Consulting

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



